### PR TITLE
Adding garage door support

### PR DESCRIPTION
**Pull request by ngori**
Adds support for garage doors.  Tested with a GoControl/Linear GD00Z-4 Z-Wave Garage Door Opener

### CODE REVIEW

**Comment by mkormendy** [comment]
@ngori I'm wondering if the unknown states might be attributed to something blocking the sensor? Is that stat-able?

**Comment by ngori** [comment]
@mkormendy I'm pretty sure they aren't a result of a sensor block.  I have a "dumb" garage door opener.  The GoControl essentially functions as an Z-wave relay.   The safety sensors in my setup have no way of communicating to the opener motor, GoControl relay, or alarm panel.  There is a small tilt sensor on the door itself that reports open/close state to the relay and then back to the panel.

There are two possible failures: 1) communication failure where the panel fails to reach the z-wave component with the state change command or 2) the sensor is blocked.  Technically a 3rd would be the tilt sensor failing or reporting incorrectly but uncommon, for my setup the panel with throw a low battery warning on the tilt sensor prior to it dying.

My experience has been if you have a sensor blockage you will receive no feedback until after ~5 attempted closes and then ADC will disable the opener on the platform and requires open/closing it with a physical local control.  So at the point ADC reports a blockage you've lost software control.

I haven't had a communication failure in quite a while. I've added an outdoor z-wave extender to overcome my solid stone wall garage but from my memory it's a similar failure mode.  Multiple tries then ADC reports a communication failure.  I don't recall what the remedy is though.  I think in that case it's just a timeout reset?

So unfortunately you have no way of knowing if the failure to change state is a result of a true senor block or comm failure until you've potentially lost software control to a block.  You could assume that close command that doesn't result in a closed state is a blockage but you can't be 100% sure.

Locks actually have a similar problem.  There is a jam state that is reported to the panel and the web interface that homebridge and the plugin currently don't capture. It isn't reported via the same mechanism as the lock/unlock states. It comes in as a popup.

**Comment by mkormendy** [comment]
My concern is about LiftMaster garage door openers .. I have a liftmaster but it's HomeKit native .. and my Alarm.com installer is impossible to get in touch with lately.

**Comment by mkormendy** [comment]
Approved. I'll be changing the repository details in the package.json in a new commit on my repo.

**Pull request merged**
